### ISSUE TITLE
Cannot Retrieve Rate - Fetching Currency Rates using ECB 

### ISSUE THREAD

**Issue by techguysourav** [LimeSoda/LimeSoda_CurrencyConverter#10]
**Summary**
Magento 1.x ECB currency update showing fatal erorr.

Preconditions
Magento 1.X

**Steps to Reproduce**

Install LimeSoda_Currency Converter in Magento
Go to   System -> Manage Currency -> Rates
Select ECB then Import button

**Expected Result**
Rates will be updated

**Actual Result**
**_Cannot retrieve rate from https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml.
Cannot retrieve rate from https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml.
Cannot retrieve rate from https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml._**
![limesoda](https://user-images.githubusercontent.com/20403436/49786573-4d3c3a00-fd4a-11e8-9550-e15e0948fc4a.PNG)

**Comment by techguysourav** [comment]
Hi,
Please can you fix this as soon as possible

**Comment by mzeis** [comment]
Hi @sourav88,

thank you for creating this issue!

I set up the extension on a fresh install of Magento 1.9.4.0 and could retrieve the rates successfully.

Please:

1. check again if the problem still exists (it might have been a temporary connection problem)
2. Add logging after [line 53 in Ecb.php](https://github.com/LimeSoda/LimeSoda_CurrencyConverter/blob/1.0.0/app/code/community/LimeSoda/CurrencyConverter/Model/Ecb.php#L53) to see if an exception is thrown. The current version of the extension doesn't log the exception which makes it more difficult to find the reason why the rate couldn't be retrieved. The error message might help you identify the cause.
3. You can also try to execute a cURL request from your server command line to check if your server can request https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml at all.

**Comment by mzeis** [comment]
Hi,

I'll close the issue due to inactivity. If you still experience the problem and you did the steps In my previous [comment](https://github.com/LimeSoda/LimeSoda_CurrencyConverter/issues/10#issuecomment-447544174), please reply here and I will be happy to re-open the issue.
