### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by nanomb** [LimeSoda/LimeSoda_CurrencyConverter#2]
Wonderful module! **Congrats!!!**

Could you please add an example of use in the Readme file? It'd be really useful.

**Comment by avoelkl** [comment]
Hi,

My colleague @wlime added usage details to the README.
Hope this is what you've been looking for.

Best regards,
Anna

**Comment by nanomb** [comment]
Thank you! I was meaning about an example in code, something like this:

```
$eurodolar = Mage::getModel('module_name/ecb')->convert('USD', 'EUR');
```

But it'd be required to have a public method if I'm not wrong.

**Comment by avoelkl** [comment]
I see.
The module here adds a service for the currency import. The `_convert` function is called from `Mage_Directory_Model_Currency_Import_Abstract` when the rates are imported. Nothing more.

The functionality you are trying to use above is a single call for conversion. This would again call the ECB webservice to fetch a rate. Calling an external webservice for a single conversion might be too much in this case i think. So it's better to access the already fetched rates this way:

```
$rates = Mage::getModel('directory/currency')->getCurrencyRates(
    Mage::app()->getStore()->getBaseCurrency(),
    Mage::app()->getStore()->getAvailableCurrencyCodes(true)
 );
```

Have a look at the `getCurrencies` method in `Mage_Directory_Block_Currency` how you can retrieve the rates from there with the `Mage::getModel('directory/currency')->getCurrencyRates()` function.

Hope this helps :)
