### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cinndra** [LimeSoda/LimeSoda_CurrencyConverter#6]
Hi Anna,
nice solution. 
Found it here since Webservicex is not working..

Since i'm not developer, please can you help me how to install this on my Magento web?

Thank you in advance!

**Comment by avoelkl** [comment]
Hi,

The usual way a developer would install this extension is:
- Install it via composer or modman on your development environment
- Test it in the development environment
- Deploy it to the test/staging system and afterwards
- Deploy it to the live system

I don't know about your setup, but basically you can just download the files from GitHub here and upload them manually via FTP.
- I **do not** recommend this way of installing as you really need to know what you're doing and where to place these files. 
- I also **don't** recommend to install it in your live-system directly. If you break anything, you're alone with this. You can break a lot if you mess up your directory structure. If you decide to do so, create at least a backup first.
- I **do** recommend to test this on your development system first and see if it works for you.
  I hope this helps.

Anyway: I think the best way to use this extension is to get a developer and let them install it for you.

**Comment by cinndra** [comment]
Hi again,
thank you for quick response. I'll try via Composer...actually I've looked in composer if the component is available but did not find anything with Search...

**Comment by avoelkl** [comment]
I don't know where you've been searching for this, but you can just add the repository URL to your `composer.json` file. If you already have a composer setup for your shop running.

**Comment by cinndra** [comment]
I've been searching in Magento Connect..
What is exact repository URL ?

**Comment by avoelkl** [comment]
No, this extension is not on Magento Connect. It's only available here on Github.
The repository URL needed for composer is: https://github.com/LimeSoda/LimeSoda_CurrencyConverter.git
