### ISSUE TITLE
Fatal Erorr - Fetching Currency Rates using ECB 

### ISSUE THREAD

**Issue by techguysourav** [LimeSoda/LimeSoda_CurrencyConverter#9]
**Summary**
Magento 1.x  ECB currency update showing fatal erorr.

**Preconditions**
Magento 1.X

**Steps to Reproduce**

1.  Install LimeSoda_Currency Converter in Magento
2. Go to   System ->  Manage Currency ->  Rates 
3.  Select ECB then  Import button  

**Expected Result**
Rates will be updated 

**Actual Result**
Fatal error: Call to undefined method LimeSoda_CurrencyConverter_Model_Ecb::_fetchRates() in /app/code/community/LimeSoda/CurrencyConverter/Model/Ecb.php on line 52

**Comment by mzeis** [comment]
Hi @sourav88,

thank you for reporting this issue and sorry for letting you wait so long!

I'm pretty sure line 52 should be: `$this->_fetchRatesFromService(1);`

We will release an updated version.

**Comment by mzeis** [comment]
Hi @sourav88, the problem should be fixed with release 1.0.0. Thanks again!
